### ISSUE TITLE
"configuring because setup_config not present" issue under Ubuntu

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/eclipsefp#257]
I have simple test program. It is compiled without any problems from the terminal with cabal. Unfortunately under EclipseFP I have issue that is similar to one issue under Windows with not finding correct Path.

I tried to run exactly the same command from the Terminal:
> varosi@ubuntu:~/workspace/test$ /home/varosi/.cabal/bin/buildwrapper thingatpoint --file=src/Main.hs --line=5 --column=9 --tempfolder=.dist-buildwrapper --cabalpath=/home/varosi/.cabal/bin/cabal --cabalfile=/home/varosi/workspace/test/test.cabal --cabalflags= --cabaloption=--with-ghc=/usr/local/bin/ghc --logcabal=true
> configuring because setup_config not present
> /home/varosi/.cabal/bin/cabal configure '--verbose=1' --enable-tests --enable-benchmarks '--builddir=/home/varosi/workspace/test/.dist-buildwrapper/dist' '--with-ghc=/usr/local/bin/ghc' --user
> 
> Segmentation fault (core dumped)
> varosi@ubuntu:~/workspace/test$ 

Please, help!

Configuration is:
* Ubuntu 14.04 (64bit)
* Haskell Platform 2014.02
* Eclipse Luna
* EclipseFP 2.6.2

**Comment by JPMoresmau** [comment]
Well known problem, that I've discussed in my blog, etc. You need to build Buildwrapper with the -dynamic flag, but that's not allowed on Hackage, so you need to change the cabal file and build it yoursef. The segfault is a GHC bug that has not been fixed in the 7.8.x branch. Maybe the 7.10 rc1 has the fix.

**Comment by varosi** [comment]
I leave EclipseFP to build it. Why isn't EclipseFP building it with that option and changing cabal file?

**Comment by JPMoresmau** [comment]
Because changing a cabal file and launching an install should be doable by any haskell developer, and I have better things to do than work around GHC bugs. One day that bug will be fixed and buildwrapper can work fine on every platform, but for now a developer can modify it if she runs into the issue, which is GHC/platform dependent.

**Comment by varosi** [comment]
Okay, thanks!

But currently this is one more thing to do by everyone with similar configuration to be able to use EclipseFP at all. I hope this GHC fix to be included in next Platform Haskell update.
